
select ORDER_NO,SOURCE_SYSTEM_NAME, SOURCE_SYSTEM_NAME from "DEMO"."PUBLIC"."SHIP_ADVICE_945"


select SHIPMENT_NUMBER,SHIPPED_DATE,EXPECTED_RECEIPT_DATE from "DEMO"."PUBLIC"."SHIPPING_NOTICE_856"