with 
using_clause AS
(
    select 
    SHIPMENT_NUMBER,
    ORGANIZATION_NAME,
    TRANSFER_ORGANIZATION_NAME,
    TRANSACTION_QUANTITY,
    TRANSACTION_UNIT_OF_MEASURE,
    ITEM,
    SUB_INVENTORY,
    TRANSFER_SUB_INVENTORY,
    TRANSACTION_DATE from {{ref('test_merge')}}
),
updates AS
(select 
 SHIPMENT_NUMBER,
    ORGANIZATION_NAME,
    TRANSFER_ORGANIZATION_NAME,
    TRANSACTION_QUANTITY,
    TRANSACTION_UNIT_OF_MEASURE,
    ITEM,
    SUB_INVENTORY,
    TRANSFER_SUB_INVENTORY,
    TRANSACTION_DATE from using_clause ),
    insert as 
    (
        select 
 SHIPMENT_NUMBER,
    ORGANIZATION_NAME,
    TRANSFER_ORGANIZATION_NAME,
    TRANSACTION_QUANTITY,
    TRANSACTION_UNIT_OF_MEASURE,
    ITEM,
    SUB_INVENTORY,
    TRANSFER_SUB_INVENTORY,
    TRANSACTION_DATE from using_clause 
    )

    select from updates 
    union insert